# Generated by scripts/generate-brew-formula.py; update from the release manifest.
class Dotasks < Formula
  desc "Local Codex task execution client"
  homepage "https://dotasks.hanzeal.com"
  url "https://dotasks.hanzeal.com/downloads/cli/0.4.1-8db4acf1ca9b/DoTasksCLI.zip"
  version "0.4.1-8db4acf1ca9b"
  sha256 "a5352e9ac48c27c8acaa1f3dcdb838f2cfe117c1830afd233cb9efe5b9e7b153"

  depends_on :macos
  depends_on "python@3.14"

  def install
    libexec.install "runtime"
    python = Formula["python@3.14"].opt_bin/"python3.14"
    (libexec/"dotasks").write <<~SH
      #!/bin/sh
      set -eu
      export DOTASKS_BREW_RUNTIME="#{opt_libexec}/runtime"
      export DOTASKS_BREW_PYTHON="#{python}"
      cd "#{opt_libexec}/runtime"
      exec "#{python}" -B -m taskboard.cli "$@"
    SH
    chmod 0755, libexec/"dotasks"
    bin.install_symlink libexec/"dotasks"
  end

  def caveats
    <<~EOS
      Run dotasks to initialize, authorize your local Codex and open the website.
      Codex must already be installed on this Mac; it is not bundled.
      When tasks are idle: dotasks stop, brew upgrade dotasks, then dotasks init.
      Before uninstalling: dotasks stop. Your account and task data are retained.
      Switching from the standalone CLI: stop it first, then run
        #{opt_bin}/dotasks install
        #{opt_bin}/dotasks init
    EOS
  end

  test do
    assert_match "team-bind", shell_output("#{bin}/dotasks --help")
    assert_match "Homebrew", shell_output("#{bin}/dotasks update --check")
  end
end
