"""Generate a pinned Homebrew formula from the verified source CLI manifest."""
import argparse
import json
from pathlib import Path
import re


def render(manifest):
    version = manifest['version']
    if not re.fullmatch(r'\d+\.\d+\.\d+-[0-9a-f]{12}', version):
        raise ValueError('Invalid release version')
    digest = manifest['sha256']
    if not re.fullmatch('[0-9a-f]{64}', digest):
        raise ValueError('Invalid release checksum')
    url = f'/downloads/cli/{version}/DoTasksCLI.zip'
    if manifest['url'] != url:
        raise ValueError('Formula requires a pinned source CLI archive')
    return '''# Generated by scripts/generate-brew-formula.py; update from the release manifest.
class Dotasks < Formula
  desc "Local Codex task execution client"
  homepage "https://dotasks.hanzeal.com"
  url "https://dotasks.hanzeal.com__URL__"
  version "__VERSION__"
  sha256 "__SHA256__"

  depends_on :macos
  depends_on "python@3.14"

  def install
    libexec.install "runtime"
    python = Formula["python@3.14"].opt_bin/"python3.14"
    (libexec/"dotasks").write <<~SH
      #!/bin/sh
      set -eu
      export DOTASKS_BREW_RUNTIME="#{opt_libexec}/runtime"
      export DOTASKS_BREW_PYTHON="#{python}"
      cd "#{opt_libexec}/runtime"
      exec "#{python}" -B -m taskboard.cli "$@"
    SH
    chmod 0755, libexec/"dotasks"
    bin.install_symlink libexec/"dotasks"
  end

  def caveats
    <<~EOS
      Run dotasks to initialize, authorize your local Codex and open the website.
      Codex must already be installed on this Mac; it is not bundled.
      When tasks are idle: dotasks stop, brew upgrade dotasks, then dotasks init.
      Before uninstalling: dotasks stop. Your account and task data are retained.
      Switching from the standalone CLI: stop it first, then run
        #{opt_bin}/dotasks install
        #{opt_bin}/dotasks init
    EOS
  end

  test do
    assert_match "team-bind", shell_output("#{bin}/dotasks --help")
    assert_match "Homebrew", shell_output("#{bin}/dotasks update --check")
  end
end
'''.replace('__URL__', url).replace('__VERSION__', version).replace('__SHA256__', digest)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--manifest', type=Path, default=Path('dist/cli/latest.json'))
    parser.add_argument('--output', type=Path, default=Path('Formula/dotasks.rb'))
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    formula = render(json.loads(args.manifest.read_text()))
    if args.check:
        if not args.output.is_file() or args.output.read_text() != formula:
            raise SystemExit('Formula differs from release. Rebuild CLI and run scripts/generate-brew-formula.py.')
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(formula)
